### ISSUE TITLE
(down) firing twice on iPad Safari version 13+

### ISSUE THREAD

**Issue by trockets** [kryops/ng2-events#5]
My company uses this library mainly for the TouchEvent module.  We found that on our iPads, after upgrading to iPadOs 13+, the (down) event would trigger our event handler twice.  We did not see this behavior on our non-upgraded tablets.  We also did not see this behavior on desktop.

iPadOs 13 brought Safari and some big changes to how iPadOs handles touch events and the 300ms delay.

**Comment by kryops** [comment]
Interestingly, I could also reproduce the same problem on a current Chrome for Android - something must have changed in the way pointer events and mouse/touch events correspond to each other when `preventDefault()` is called.

iOS 13 brought support for pointer events, so that would explain why the upgrade changed its behavior.

@ambiguousFoo could you try out `v4.2.1` and check if that fixes the problem for you? I added some logic to attach mouse and touch event handlers only if the device does not support pointer events.

**Comment by trockets** [comment]
Thankyou @kryops , your commit fixed my issue.  Everything works great!
